version: '3'

services:
  nginx:
    build: ./nginx
    image: chatting_nginx:latest
    volumes:
      - static_volume:/usr/src/app/_static
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
  web:
    build: .
    image: chatting_web:latest
    command: daphne -b 0.0.0.0 -p 8000 meong_signal.asgi:application
    volumes:
      - static_volume:/usr/src/app/_static
      - ./:/usr/src/app/
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  redis:
    image: redis:alpine # 이렇게 해시를 태그로 사용합니다.
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  static_volume: