#docker-compose.yml

version: "3"

services:
  nginx:
    build: ./nginx
    image: meong_signal_nginx:latest
    volumes:
      - static_volume:/usr/src/app/_static
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
  web:
    build: .
    image: meong_signal:latest
    command: daphne meong_signal.asgi:application --port 8000 --bind 0.0.0.0 -v2
    volumes:
      - static_volume:/usr/src/app/_static
      - ./:/usr/src/app/
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  static_volume:
